[package]
name = "rak_rs"
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace]
members = [
    "plugin_api",
    "examples/sample_plugin",
    "examples/validation_plugin",
    "examples/validation_unloader",
]
default-members = ["."]
resolver = "2"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.4"

[dependencies]
log = "0.4"
rak_rs_plugin_api = { package = "rak_rs_plugin_api", path = "plugin_api" }
simplelog = "0.12"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Memory",
    "Win32_System_SystemServices",
] }

[target.'cfg(all(windows, target_arch = "x86"))'.dependencies]
minhook = "0.9"
