[package]
name = "rak_samp_validation_plugin"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
rak_samp_plugin_api = { path = "../../plugin_api" }
simplelog = "0.12"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
] }
