[package]
name = "rak_samp_e2e_plugin"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rak_samp_plugin_api = { path = "../../../plugin_api" }
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
] }
