mod fixed;
mod r1;
mod types;

pub use fixed::*;
pub use r1::*;
pub use types::*;

use crate::events::core::handle;
use crate::events::{EventError, RpcAction, Vector3};
use crate::{HostApi, RakSampEventV1, RakSampHookAction};

/// Handles `onServerMessage` from an incoming raw RPC callback.
///
/// # Safety
///
/// See [`crate::events::handle`].
#[allow(dead_code)]
pub(crate) unsafe fn on_server_message(
    api: HostApi,
    raw: *mut RakSampEventV1,
    handler: impl FnOnce(ServerMessage) -> RpcAction<ServerMessage>,
) -> Result<RakSampHookAction, EventError> {
    unsafe { handle(api, raw, SERVER_MESSAGE, handler) }
}

macro_rules! rpc_helper {
    ($name:ident, $value:ty, $rpc:ident, $event_name:literal) => {
        #[doc = concat!("Handles MoonLoader's `", $event_name, "` from an incoming raw RPC callback.")]
        ///
        /// # Safety
        ///
        /// See [`crate::events::handle`].
        #[allow(dead_code)]
        pub(crate) unsafe fn $name(
            api: HostApi,
            raw: *mut RakSampEventV1,
            handler: impl FnOnce($value) -> RpcAction<$value>,
        ) -> Result<RakSampHookAction, EventError> {
            unsafe { handle(api, raw, $rpc, handler) }
        }
    };
}

rpc_helper!(
    on_display_game_text,
    GameText,
    DISPLAY_GAME_TEXT,
    "onDisplayGameText"
);
rpc_helper!(on_show_dialog, ShowDialog, SHOW_DIALOG, "onShowDialog");
rpc_helper!(on_set_player_pos, Vector3, SET_PLAYER_POS, "onSetPlayerPos");
rpc_helper!(
    on_set_player_pos_find_z,
    Vector3,
    SET_PLAYER_POS_FIND_Z,
    "onSetPlayerPosFindZ"
);
rpc_helper!(
    on_set_player_health,
    f32,
    SET_PLAYER_HEALTH,
    "onSetPlayerHealth"
);
rpc_helper!(
    on_set_player_armour,
    f32,
    SET_PLAYER_ARMOUR,
    "onSetPlayerArmour"
);
rpc_helper!(
    on_set_player_facing_angle,
    f32,
    SET_PLAYER_FACING_ANGLE,
    "onSetPlayerFacingAngle"
);
rpc_helper!(
    on_toggle_player_controllable,
    bool,
    TOGGLE_PLAYER_CONTROLLABLE,
    "onTogglePlayerControllable"
);
rpc_helper!(on_play_sound, PlaySound, PLAY_SOUND, "onPlaySound");
rpc_helper!(
    on_set_checkpoint,
    Checkpoint,
    SET_CHECKPOINT,
    "onSetCheckpoint"
);
rpc_helper!(on_chat_message, ChatMessage, CHAT_MESSAGE, "onChatMessage");
rpc_helper!(
    on_player_chat_bubble,
    ChatBubble,
    CHAT_BUBBLE,
    "onPlayerChatBubble"
);
rpc_helper!(on_player_join, PlayerJoin, PLAYER_JOIN, "onPlayerJoin");
rpc_helper!(on_player_quit, PlayerQuit, PLAYER_QUIT, "onPlayerQuit");
rpc_helper!(
    on_set_player_name,
    PlayerName,
    SET_PLAYER_NAME,
    "onSetPlayerName"
);
rpc_helper!(
    on_set_player_time,
    PlayerTime,
    SET_PLAYER_TIME,
    "onSetPlayerTime"
);
rpc_helper!(on_cancel_edit, (), CANCEL_EDIT, "onCancelEdit");
rpc_helper!(
    on_set_toggle_clock,
    bool,
    SET_TOGGLE_CLOCK,
    "onSetToggleClock"
);
rpc_helper!(
    on_set_player_drunk,
    i32,
    SET_PLAYER_DRUNK,
    "onSetPlayerDrunk"
);
rpc_helper!(
    on_set_race_checkpoint,
    RaceCheckpoint,
    SET_RACE_CHECKPOINT,
    "onSetRaceCheckpoint"
);
rpc_helper!(
    on_play_audio_stream,
    AudioStream,
    PLAY_AUDIO_STREAM,
    "onPlayAudioStream"
);
rpc_helper!(
    on_set_object_position,
    ObjectPosition,
    SET_OBJECT_POSITION,
    "onSetObjectPosition"
);
rpc_helper!(
    on_set_object_rotation,
    ObjectRotation,
    SET_OBJECT_ROTATION,
    "onSetObjectRotation"
);
rpc_helper!(on_destroy_object, u16, DESTROY_OBJECT, "onDestroyObject");
rpc_helper!(
    on_player_death_notification,
    PlayerDeathNotification,
    PLAYER_DEATH_NOTIFICATION,
    "onPlayerDeathNotification"
);
rpc_helper!(on_set_map_icon, MapIcon, SET_MAP_ICON, "onSetMapIcon");
rpc_helper!(
    on_remove_vehicle_component,
    VehicleComponent,
    REMOVE_VEHICLE_COMPONENT,
    "onRemoveVehicleComponent"
);
rpc_helper!(
    on_remove_3d_text_label,
    u16,
    REMOVE_3D_TEXT_LABEL,
    "onRemove3DTextLabel"
);
rpc_helper!(
    on_update_global_timer,
    i32,
    UPDATE_GLOBAL_TIMER,
    "onUpdateGlobalTimer"
);
rpc_helper!(on_destroy_pickup, i32, DESTROY_PICKUP, "onDestroyPickup");
rpc_helper!(
    on_link_vehicle_to_interior,
    VehicleInterior,
    LINK_VEHICLE_TO_INTERIOR,
    "onLinkVehicleToInterior"
);
rpc_helper!(
    on_set_player_color,
    PlayerColor,
    SET_PLAYER_COLOR,
    "onSetPlayerColor"
);
rpc_helper!(
    on_request_spawn_response,
    bool,
    REQUEST_SPAWN_RESPONSE,
    "onRequestSpawnResponse"
);
rpc_helper!(on_set_shop_name, [u8; 32], SET_SHOP_NAME, "onSetShopName");
rpc_helper!(
    on_set_player_skill_level,
    PlayerSkill,
    SET_PLAYER_SKILL_LEVEL,
    "onSetPlayerSkillLevel"
);
rpc_helper!(
    on_remove_building,
    RemoveBuilding,
    REMOVE_BUILDING,
    "onRemoveBuilding"
);
rpc_helper!(
    on_attach_object_to_player,
    AttachObjectToPlayer,
    ATTACH_OBJECT_TO_PLAYER,
    "onAttachObjectToPlayer"
);
rpc_helper!(on_show_menu, u8, SHOW_MENU, "onShowMenu");
rpc_helper!(on_hide_menu, u8, HIDE_MENU, "onHideMenu");
rpc_helper!(
    on_create_explosion,
    Explosion,
    CREATE_EXPLOSION,
    "onCreateExplosion"
);
rpc_helper!(
    on_show_player_name_tag,
    PlayerNameTag,
    SHOW_PLAYER_NAME_TAG,
    "onShowPlayerNameTag"
);
rpc_helper!(
    on_attach_camera_to_object,
    u16,
    ATTACH_CAMERA_TO_OBJECT,
    "onAttachCameraToObject"
);
rpc_helper!(
    on_gang_zone_stop_flash,
    u16,
    GANG_ZONE_STOP_FLASH,
    "onGangZoneStopFlash"
);
rpc_helper!(
    on_clear_player_animation,
    u16,
    CLEAR_PLAYER_ANIMATION,
    "onClearPlayerAnimation"
);
rpc_helper!(
    on_set_player_special_action,
    u8,
    SET_PLAYER_SPECIAL_ACTION,
    "onSetPlayerSpecialAction"
);
rpc_helper!(
    on_set_player_fighting_style,
    PlayerFightingStyle,
    SET_PLAYER_FIGHTING_STYLE,
    "onSetPlayerFightingStyle"
);
rpc_helper!(
    on_set_player_velocity,
    Vector3,
    SET_PLAYER_VELOCITY,
    "onSetPlayerVelocity"
);
rpc_helper!(
    on_set_vehicle_velocity,
    VehicleVelocity,
    SET_VEHICLE_VELOCITY,
    "onSetVehicleVelocity"
);
rpc_helper!(on_create_pickup, Pickup, CREATE_PICKUP, "onCreatePickup");
rpc_helper!(on_move_object, MoveObject, MOVE_OBJECT, "onMoveObject");
rpc_helper!(
    on_text_draw_set_string,
    TextDrawString,
    TEXT_DRAW_SET_STRING,
    "onTextDrawSetString"
);
rpc_helper!(
    on_create_gang_zone,
    GangZone,
    CREATE_GANG_ZONE,
    "onCreateGangZone"
);
rpc_helper!(
    on_gang_zone_destroy,
    u16,
    GANG_ZONE_DESTROY,
    "onGangZoneDestroy"
);
rpc_helper!(
    on_gang_zone_flash,
    (u16, i32),
    GANG_ZONE_FLASH,
    "onGangZoneFlash"
);
rpc_helper!(on_stop_object, u16, STOP_OBJECT, "onStopObject");
rpc_helper!(
    on_set_vehicle_number_plate,
    VehicleNumberPlate,
    SET_VEHICLE_NUMBER_PLATE,
    "onSetVehicleNumberPlate"
);
rpc_helper!(
    on_spectate_player,
    Spectate,
    SPECTATE_PLAYER,
    "onSpectatePlayer"
);
rpc_helper!(
    on_spectate_vehicle,
    Spectate,
    SPECTATE_VEHICLE,
    "onSpectateVehicle"
);
rpc_helper!(
    on_connection_rejected,
    u8,
    CONNECTION_REJECTED,
    "onConnectionRejected"
);
rpc_helper!(on_remove_map_icon, u8, REMOVE_MAP_ICON, "onRemoveMapIcon");
rpc_helper!(
    on_set_weapon_ammo,
    WeaponAmmo,
    SET_WEAPON_AMMO,
    "onSetWeaponAmmo"
);
rpc_helper!(on_set_gravity, f32, SET_GRAVITY, "onSetGravity");
rpc_helper!(
    on_attach_trailer_to_vehicle,
    TrailerAttachment,
    ATTACH_TRAILER_TO_VEHICLE,
    "onAttachTrailerToVehicle"
);
rpc_helper!(
    on_detach_trailer_from_vehicle,
    u16,
    DETACH_TRAILER_FROM_VEHICLE,
    "onDetachTrailerFromVehicle"
);
rpc_helper!(
    on_set_camera_position,
    Vector3,
    SET_CAMERA_POSITION,
    "onSetCameraPosition"
);
rpc_helper!(
    on_set_camera_look_at,
    CameraLookAt,
    SET_CAMERA_LOOK_AT,
    "onSetCameraLookAt"
);
rpc_helper!(
    on_set_vehicle_params,
    VehicleParams,
    SET_VEHICLE_PARAMS,
    "onSetVehicleParams"
);
rpc_helper!(on_player_death, u16, PLAYER_DEATH, "onPlayerDeath");
rpc_helper!(
    on_player_enter_vehicle,
    PlayerEnterVehicle,
    PLAYER_ENTER_VEHICLE,
    "onPlayerEnterVehicle"
);
rpc_helper!(
    on_player_exit_vehicle,
    PlayerExitVehicle,
    PLAYER_EXIT_VEHICLE,
    "onPlayerExitVehicle"
);
rpc_helper!(on_client_check, ClientCheck, CLIENT_CHECK, "onClientCheck");
rpc_helper!(
    on_set_vehicle_params_ex,
    VehicleParamsEx,
    SET_VEHICLE_PARAMS_EX,
    "onSetVehicleParamsEx"
);
rpc_helper!(
    on_vehicle_tuning_notification,
    VehicleTuningNotification,
    VEHICLE_TUNING_NOTIFICATION,
    "onVehicleTuningNotification"
);
rpc_helper!(
    on_set_vehicle_tires,
    (u16, u8),
    SET_VEHICLE_TIRES,
    "onSetVehicleTires"
);
rpc_helper!(
    on_vehicle_damage_status_update,
    VehicleDamageStatus,
    VEHICLE_DAMAGE_STATUS_UPDATE,
    "onVehicleDamageStatusUpdate"
);
rpc_helper!(
    on_toggle_widescreen,
    bool,
    TOGGLE_WIDESCREEN,
    "onToggleWidescreen"
);
rpc_helper!(on_destroy_actor, u16, DESTROY_ACTOR, "onDestroyActor");
rpc_helper!(
    on_destroy_weapon_pickup,
    u8,
    DESTROY_WEAPON_PICKUP,
    "onDestroyWeaponPickup"
);
rpc_helper!(
    on_edit_attached_object,
    i32,
    EDIT_ATTACHED_OBJECT,
    "onEditAttachedObject"
);
rpc_helper!(
    on_enter_select_object,
    (),
    ENTER_SELECT_OBJECT,
    "onEnterSelectObject"
);
rpc_helper!(
    on_server_statistics_response,
    (),
    SERVER_STATISTICS_RESPONSE,
    "onServerStatisticsResponse"
);
rpc_helper!(
    on_set_player_drunk_visuals,
    i32,
    SET_PLAYER_DRUNK_VISUALS,
    "onSetPlayerDrunkVisuals"
);
rpc_helper!(
    on_set_player_drunk_handling,
    i32,
    SET_PLAYER_DRUNK_HANDLING,
    "onSetPlayerDrunkHandling"
);
rpc_helper!(on_create_actor, Actor, CREATE_ACTOR, "onCreateActor");
rpc_helper!(
    on_clear_actor_animation,
    u16,
    CLEAR_ACTOR_ANIMATION,
    "onClearActorAnimation"
);
rpc_helper!(
    on_set_actor_facing_angle,
    ActorAngle,
    SET_ACTOR_FACING_ANGLE,
    "onSetActorFacingAngle"
);
rpc_helper!(
    on_set_actor_position,
    ActorPosition,
    SET_ACTOR_POSITION,
    "onSetActorPos"
);
rpc_helper!(
    on_set_actor_health,
    ActorHealth,
    SET_ACTOR_HEALTH,
    "onSetActorHealth"
);
rpc_helper!(
    on_set_player_object_no_camera_col,
    u16,
    SET_PLAYER_OBJECT_NO_CAMERA_COL,
    "onSetPlayerObjectNoCameraCol"
);
rpc_helper!(
    on_set_world_bounds,
    WorldBounds,
    SET_WORLD_BOUNDS,
    "onSetWorldBounds"
);
rpc_helper!(
    on_give_player_money,
    i32,
    GIVE_PLAYER_MONEY,
    "onGivePlayerMoney"
);
rpc_helper!(
    on_give_player_weapon,
    PlayerWeapon,
    GIVE_PLAYER_WEAPON,
    "onGivePlayerWeapon"
);
rpc_helper!(on_set_world_time, u8, SET_WORLD_TIME, "onSetWorldTime");
rpc_helper!(on_set_weather, u8, SET_WEATHER, "onSetWeather");
rpc_helper!(
    on_set_player_skin,
    PlayerSkin,
    SET_PLAYER_SKIN,
    "onSetPlayerSkin"
);
rpc_helper!(on_set_interior, u8, SET_INTERIOR, "onSetInterior");
rpc_helper!(
    on_set_player_armed_weapon,
    i32,
    SET_PLAYER_ARMED_WEAPON,
    "onSetPlayerArmedWeapon"
);
rpc_helper!(
    on_set_player_wanted_level,
    u8,
    SET_PLAYER_WANTED_LEVEL,
    "onSetPlayerWantedLevel"
);
rpc_helper!(
    on_set_player_team,
    PlayerTeam,
    SET_PLAYER_TEAM,
    "onSetPlayerTeam"
);
rpc_helper!(
    on_put_player_in_vehicle,
    PutPlayerInVehicle,
    PUT_PLAYER_IN_VEHICLE,
    "onPutPlayerInVehicle"
);
rpc_helper!(
    on_player_stream_out,
    u16,
    PLAYER_STREAM_OUT,
    "onPlayerStreamOut"
);
rpc_helper!(
    on_vehicle_stream_out,
    u16,
    VEHICLE_STREAM_OUT,
    "onVehicleStreamOut"
);
rpc_helper!(
    on_set_vehicle_position,
    VehiclePosition,
    SET_VEHICLE_POSITION,
    "onSetVehiclePosition"
);
rpc_helper!(
    on_set_vehicle_angle,
    VehicleAngle,
    SET_VEHICLE_ANGLE,
    "onSetVehicleAngle"
);
rpc_helper!(
    on_set_vehicle_health,
    VehicleHealth,
    SET_VEHICLE_HEALTH,
    "onSetVehicleHealth"
);
rpc_helper!(
    on_reset_player_money,
    (),
    RESET_PLAYER_MONEY,
    "onResetPlayerMoney"
);
rpc_helper!(
    on_reset_player_weapons,
    (),
    RESET_PLAYER_WEAPONS,
    "onResetPlayerWeapons"
);
rpc_helper!(
    on_disable_checkpoint,
    (),
    DISABLE_CHECKPOINT,
    "onDisableCheckpoint"
);
rpc_helper!(
    on_disable_race_checkpoint,
    (),
    DISABLE_RACE_CHECKPOINT,
    "onDisableRaceCheckpoint"
);
rpc_helper!(
    on_gamemode_restart,
    (),
    GAMEMODE_RESTART,
    "onGamemodeRestart"
);
rpc_helper!(
    on_stop_audio_stream,
    (),
    STOP_AUDIO_STREAM,
    "onStopAudioStream"
);
rpc_helper!(
    on_remove_player_from_vehicle,
    (),
    REMOVE_PLAYER_FROM_VEHICLE,
    "onRemovePlayerFromVehicle"
);
rpc_helper!(
    on_force_class_selection,
    (),
    FORCE_CLASS_SELECTION,
    "onForceClassSelection"
);
rpc_helper!(
    on_set_camera_behind,
    (),
    SET_CAMERA_BEHIND,
    "onSetCameraBehind"
);
rpc_helper!(on_init_game, InitGame, INIT_GAME, "onInitGame");
rpc_helper!(
    on_request_class_response,
    RequestClassResponse,
    REQUEST_CLASS_RESPONSE,
    "onRequestClassResponse"
);
rpc_helper!(
    on_player_stream_in,
    PlayerStreamIn,
    PLAYER_STREAM_IN,
    "onPlayerStreamIn"
);
rpc_helper!(
    on_create_3d_text,
    TextLabel3D,
    CREATE_3D_TEXT,
    "onCreate3DText"
);
rpc_helper!(on_create_object, Object, CREATE_OBJECT, "onCreateObject");
rpc_helper!(
    on_set_spawn_info,
    SpawnInfo,
    SET_SPAWN_INFO,
    "onSetSpawnInfo"
);
rpc_helper!(on_init_menu, InitMenu, INIT_MENU, "onInitMenu");
rpc_helper!(
    on_interpolate_camera,
    InterpolateCamera,
    INTERPOLATE_CAMERA,
    "onInterpolateCamera"
);
rpc_helper!(
    on_toggle_select_text_draw,
    ToggleSelectTextDraw,
    TOGGLE_SELECT_TEXT_DRAW,
    "onToggleSelectTextDraw"
);
rpc_helper!(
    on_set_object_material,
    ObjectMaterialUpdate,
    SET_OBJECT_MATERIAL,
    "onSetObjectMaterial/onSetObjectMaterialText"
);
rpc_helper!(
    on_apply_player_animation,
    PlayerAnimation,
    APPLY_PLAYER_ANIMATION,
    "onApplyPlayerAnimation"
);
rpc_helper!(
    on_enable_stunt_bonus,
    bool,
    ENABLE_STUNT_BONUS,
    "onEnableStuntBonus"
);
rpc_helper!(
    on_play_crime_report,
    CrimeReport,
    PLAY_CRIME_REPORT,
    "onPlayCrimeReport"
);
rpc_helper!(
    on_set_player_attached_object,
    PlayerAttachedObject,
    SET_PLAYER_ATTACHED_OBJECT,
    "onSetPlayerAttachedObject"
);
rpc_helper!(
    on_enter_edit_object,
    EnterEditObject,
    ENTER_EDIT_OBJECT,
    "onEnterEditObject"
);
rpc_helper!(
    on_toggle_player_spectating,
    bool,
    TOGGLE_PLAYER_SPECTATING,
    "onTogglePlayerSpectating"
);
rpc_helper!(
    on_show_text_draw,
    ShowTextDraw,
    SHOW_TEXT_DRAW,
    "onShowTextDraw"
);
rpc_helper!(on_text_draw_hide, u16, TEXT_DRAW_HIDE, "onTextDrawHide");
rpc_helper!(
    on_update_scores_and_pings,
    ScoresAndPings,
    UPDATE_SCORES_AND_PINGS,
    "onUpdateScoresAndPings"
);
rpc_helper!(
    on_vehicle_stream_in,
    VehicleStreamIn,
    VEHICLE_STREAM_IN,
    "onVehicleStreamIn"
);
rpc_helper!(
    on_disable_vehicle_collisions,
    bool,
    DISABLE_VEHICLE_COLLISIONS,
    "onDisableVehicleCollisions"
);
rpc_helper!(
    on_toggle_camera_target_notifying,
    bool,
    TOGGLE_CAMERA_TARGET_NOTIFYING,
    "onToggleCameraTargetNotifying"
);
rpc_helper!(
    on_apply_actor_animation,
    ActorAnimation,
    APPLY_ACTOR_ANIMATION,
    "onApplyActorAnimation"
);
