[package]
name = "samp-client-sdk-r5-network-probe"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[features]
r1-probe = []
r3-probe = []
dl-probe = []

[lib]
crate-type = ["cdylib"]

[dependencies]
samp_client_sdk = { package = "samp-client-sdk", path = "../../sdk" }
samp-protocol = { path = "../../crates/samp-protocol" }
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
] }
