[package]
name = "rak_rs_sample_plugin"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
rak_rs_plugin_api = { path = "../../plugin_api" }
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
] }
